In [2]:
pip install numpy

   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.3 MB 3.0 MB/s eta 0:00:04
   ---- ----------------------------------- 1.3/12.3 MB 3.6 MB/s eta 0:00:04
   ----- ---------------------------------- 1.8/12.3 MB 3.4 MB/s eta 0:00:04
   ----- ---------------------------------- 1.8/12.3 MB 3.4 MB/s eta 0:00:04
   -------- ------------------------------- 2.6/12.3 MB 2.9 MB/s eta 0:00:04
   ----------- ---------------------------- 3.4/12.3 MB 2.7 MB/s eta 0:00:04
   ----------- ---------------------------- 3.4/12.3 MB 2.7 MB/s eta 0:00:04
   ----------- ---------------------------- 3.7/12.3 MB 2.3 MB/s eta 0:00:04
   -------------- ------------------------- 4.5/12.3 MB 2.5 MB/s eta 0:00:04
   ----------------- ---------------------- 5.2/12.3 MB 2.6 MB/s eta 0:00:03
   ------------------ --------------------- 5.8/12.3 MB 2.5 MB/s eta 0:00:03
   ----------

In [2]:
#1. Create a 1D NumPy array of numbers from 10 to 50 with step 5


import numpy as np

arr1 = np.arange(10,51,5)
print(arr1)

[10 15 20 25 30 35 40 45 50]


In [3]:
# 2. Create a 4×6 array of zeros and fill its third row (index 2) with 99

arr = np.zeros((4, 6))
arr[2] = 99
print(arr)

[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [99. 99. 99. 99. 99. 99.]
 [ 0.  0.  0.  0.  0.  0.]]


In [4]:
# 3. Given the array, print all elements greater than 50

arr = np.array([12, 45, 7, 19, 88, 3, 56, 91, 24, 67])

arr_grt_50 = arr[arr>50]
print(arr_grt_50)

[88 56 91 67]


In [5]:
# 4. Create a 5×5 identity matrix and change the diagonal to [10, 20, 30, 40, 50]

arr = np.eye(5)
np.fill_diagonal(arr,[10, 20, 30 ,40, 50])
print(arr)

[[10.  0.  0.  0.  0.]
 [ 0. 20.  0.  0.  0.]
 [ 0.  0. 30.  0.  0.]
 [ 0.  0.  0. 40.  0.]
 [ 0.  0.  0.  0. 50.]]


In [10]:
# 5. Let x = np.arange(1, 21).reshape(4, 5)
# (a) The last two rows
# (b) The third column
# (c) The 3×3 submatrix in the top-right corner

x = np.arange(1, 21).reshape(4, 5)
print(x)

# (a) The last two rows
print(x[-2:,:])

# (b) The third column
third_col=x[:,2]

# (c) The 3×3 submatrix in the top-right corner
submatrix = x[:3,2:]
print(submatrix)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[11 12 13 14 15]
 [16 17 18 19 20]]
[[ 3  4  5]
 [ 8  9 10]
 [13 14 15]]


In [11]:
# 6. Given arrays a and b, compute a + b and explain shape
a = np.array([1, 2, 3, 4])
b = np.array([[10], [20], [30]])

res = a + b

print(res)
print(res.shape)


[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]
(3, 4)


In [12]:
# 7. Normalize the array to range [0, 1]
data = np.array([150, 220, 98, 360, 180, 45])

normalized_data = (data - data.min())/ (data.max() - data.min())
print(normalized_data)

[0.33333333 0.55555556 0.16825397 1.         0.42857143 0.        ]


In [14]:
# 8. Standardize (z-score) the same array from Question 7
mean = data.mean()
std = data.std()

standardized_data = (data - mean) / std
print(standardized_data)

[-0.25558104  0.44601398 -0.77676591  1.84920401  0.04510254 -1.30797357]


In [15]:
# 9. Given the 2D array
    
mat = np.array([
    [4, 8, 1, 12],
    [7, 3, 9, 5],
    [11, 2, 6, 10],
    [15, 0, 14, 13]
])

# a. Compute the mean of each row
mat_row_mean = mat.mean(axis=1)

# b. Compute the sum of each column
mat_col_sum = mat.sum(axis= 0)

# c. Find the maximum value in the matrix and its position
mat_max_v = mat.max()

max_val_pos = np.unravel_index(mat.argmax(), mat.shape)
print(mat)
print(mat_row_mean)
print(mat_col_sum)
print(mat_max_v)
print(max_val_pos)

[[ 4  8  1 12]
 [ 7  3  9  5]
 [11  2  6 10]
 [15  0 14 13]]
[ 6.25  6.    7.25 10.5 ]
[37 13 30 40]
15
(np.int64(3), np.int64(0))


In [16]:
# 10.Reshape np.arange(36) into shape (3, 4, 3)
arr = np.arange(36).reshape(3, 4 ,3)
print(arr)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]


In [18]:
#  11. Reverse rows and columns of
arr = np.arange(1, 17).reshape(4, 4)

arr_reversed = arr[::-1, ::-1]
print(arr_reversed)

[[16 15 14 13]
 [12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [ ]:
# 12. Given:
ages = np.array([23, 45, 19, 34, 28, 51, 17, 39])
names = np.array(["Ali", "Sara", "Omar", "Lina", "Khaled", "Nour", "Yara", "Hassan"])

# a. Get the names of people whose age is between 25 and 40 (inclusive).
mask = (ages>= 25) & (ages <= 40)
res = names[mask]
print(res)







['Lina' 'Khaled' 'Hassan']


In [20]:
#13. Using the same ages and names arrays
# Replace all ages less than 20 with 20

ages[ages <20] = 20
print(ages)


[23 45 20 34 28 51 20 39]


In [21]:
# 14. Create a 6×6 array of random integers from 1 to 100 (inclusive)
# Then set the seed to 123 first.

np.random.seed(123)
random_arr = np.random.randint(1, 101, size=((6 , 6)))
print(random_arr)


[[ 67  93  99  18  84  58]
 [ 87  98  97  48  74  33]
 [ 47  97  26  84  79  37]
 [ 97  81  69  50  56  68]
 [  3  85  40  67  85  48]
 [ 62  49   8 100  93  53]]


In [22]:
# 15. Create an array of 10 random numbers from a normal distribution with mean 100 and std 15
normal_arr = np.random.normal(100, 15, 10)
print(normal_arr)


[127.06686834  85.51674961  80.25279948  90.61322265  95.09580659
  95.37686206 112.40676196 116.06172126  54.16633874 115.08897902]


In [26]:
#16. From the list
colors = ["red", "blue", "green", "yellow", "purple"]

# Randomly select 3 different colors without replacement
# Pythonchoice = np.random.choice(colors, 3, replace=False)
choice = np.random.choice(colors, 3, replace=False)
print(choice)


['purple' 'yellow' 'red']


In [28]:
# 17. Shuffle the numbers from 1 to 20 in place
arr = np.arange(1, 21)
np.random.shuffle(arr)
print(arr)



[ 5  9 15  1 13  3  6  2 19 11 14 16 18 17  8 10  7 20 12  4]
